name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build -x test -x spotlessCheck

      - name: Run JUnit tests
        run: ./gradlew test

      - name: Check formatting
        run: ./gradlew spotlessCheck
